AROME:
    n_member: 17 #include member 0 if available !
    n_lon: 1121
    n_lat: 717
    membre0: True
    limit_inf: 1 #first lead time
    limit_sup: 51 #last one
    no_data_threshold: 9998.
    Limit_EURW1S40: [37.5,55.4,-12.0,16.0] #latitude_min, latitude_max, longitude_min, longitude_max
    Resolution_EURW1S40: 0.025

Zoom:
    Size_X: 384 # nb grid points(longitude)
    Size_Y: 256 # nb grid points (latitude)
    NW: [230,300] #X_min, Y_min
    NE: [460,300]
    SW: [250,150]
    SE: [540,120]
    C: [360,220]

Object_detection:
   name: ['tot','mod','heavy']
   radius: [15,12,10] #for total,moderate and heavy objects (in grid points)
   threshold: [0.2,3.,7.] #for total,moderate and heavy objects (in mm)

val_database:
   begin: '2021010103' #date YYYYMMDD + runtime HH
   end: '2021123103'
   delta_run: '24'
   List_MB: [1,4] #first and last AROME-EPS member in the validation database

path_data_IA: '/path_IA/...'
path_attributs_IA: '/path_object_attribut_IA/'

path_data_EPS: '/path_EPS/...'
path_attributs_EPS: '/path_object_attribut_EPS/...'

path_scores: '/path_save_scores/...'

